# use Ganache's forked mainnet mode as the default network
networks:
  default: development

autofetch_sources: true

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.1

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.16
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.1"

reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath
    - SafeERC20
    - Address
